### ISSUE TITLE
Runelite crash array out of bounds

### ISSUE THREAD

**Issue by Ikreb1** [larsvansoest/emote-clue-items#26]
Happens only while playing with multiple clients

2021-10-03 15:05:33 [Client] INFO  c.f.controller.FlippingPlugin - starting slot timers on login
2021-10-03 15:05:33 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.ArrayIndexOutOfBoundsException: Index 13 out of bounds for length 13
	at com.larsvansoest.runelite.clueitems.progress.ItemTracker.writeDeltas(ItemTracker.java:62)
	at com.larsvansoest.runelite.clueitems.progress.InventoryMonitor.fetchEmoteClueItemChanges(InventoryMonitor.java:74)
	at com.larsvansoest.runelite.clueitems.progress.ProgressManager.processInventoryChanges(ProgressManager.java:110)
	at com.larsvansoest.runelite.clueitems.EmoteClueItemsPlugin.onItemContainerChanged(EmoteClueItemsPlugin.java:188)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.util.DeferredEventBus.replay(DeferredEventBus.java:69)
	at net.runelite.client.callback.Hooks.updateNpcs(Hooks.java:487)
	at client.zh(client.java:23611)
	at ev.hc(ev.java)
	at client.di(client.java:7413)
	at client.fz(client.java:3659)
	at client.i(client.java:1893)
	at at.jr(at.java:380)
	at at.run(at.java:359)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by larsvansoest** [comment]
Thanks for letting me know! Will look into it!

**Comment by larsvansoest** [comment]
Seems like the bug occurred while trying to fetch your account's equipment. The error shows that there were 13 item changes at once, which should not be possible. 

I have a hard time trying to reproduce your issue. Would you be able to tell me more about when this bug occurred? For instance, did you stash your equipment in the bank? And, what actions were you performing on multiple clients at once? With this information, I hope to accurately investigate the issue!

**Comment by Ikreb1** [comment]
I'm sorry. Not quite sure what was happening, this happened alot. I had 3 clients open.
I was also having some problems with other plugins and I figure out that it was the gpu plugin that was crashing my game not this one.
Error might have been unrelated to your plugin.
These where the settings I had in the plugin:
![image](https://user-images.githubusercontent.com/38193851/135883555-083313b5-6120-40c0-b376-523a3076be5b.png)

**Comment by larsvansoest** [comment]
Thanks for the follow up! Hmm, maybe you're right, perhaps there was some lag and somehow the item tracking got messed up. Anyways, it seems like more equipment slot 13 had a change, but I don't think there are that many. Perhaps another plugin triggered the false event? If this bug occurs more often, please let me know, and I could perhaps implement a fail safe that won't make your runelite crash.

**Comment by larsvansoest** [comment]
I am closing this issue until further notice. If you manage to reproduce this error, please let me know!
